import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import Database from "better-sqlite3";
import { GoogleGenAI, Type } from "@google/genai";
import crypto from "crypto";

dotenv.config();

const app = express();

app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 3000;

// Verify Gemini API Key
if (!process.env.GEMINI_API_KEY) {
  console.error("ERROR: GEMINI_API_KEY is missing from environment variables");
  process.exit(1);
}

// Initialize Gemini Client
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });


// ============================================================
// DATABASE
// ============================================================

const db = new Database("quiz.db");

db.pragma("journal_mode = WAL");

db.exec(`
  CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS questions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    question_hash TEXT NOT NULL,
    subject TEXT NOT NULL,
    difficulty TEXT NOT NULL,
    question TEXT NOT NULL,
    options TEXT NOT NULL,
    correct_answer INTEGER NOT NULL,
    explanation TEXT NOT NULL,
    created_at TEXT NOT NULL,

    FOREIGN KEY(user_id)
      REFERENCES users(id)
  );

  CREATE INDEX IF NOT EXISTS idx_questions_user
  ON questions(user_id);

  CREATE INDEX IF NOT EXISTS idx_questions_hash
  ON questions(question_hash);
`);


// ============================================================
// HELPERS
// ============================================================

function normalizeQuestion(question) {
  return question
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();
}

function hashQuestion(question) {
  return crypto
    .createHash("sha256")
    .update(normalizeQuestion(question))
    .digest("hex");
}

function ensureUser(userId) {
  const existing = db
    .prepare("SELECT id FROM users WHERE id = ?")
    .get(userId);

  if (!existing) {
    db.prepare(`
      INSERT INTO users (id, created_at)
      VALUES (?, ?)
    `).run(userId, new Date().toISOString());
  }
}

function getPreviousQuestions(userId) {
  return db
    .prepare(`
      SELECT question
      FROM questions
      WHERE user_id = ?
      ORDER BY created_at DESC
      LIMIT 500
    `)
    .all(userId)
    .map((row) => row.question);
}

function questionAlreadyExists(userId, questionHash) {
  const result = db
    .prepare(`
      SELECT id
      FROM questions
      WHERE user_id = ?
      AND question_hash = ?
      LIMIT 1
    `)
    .get(userId, questionHash);

  return !!result;
}


// ============================================================
// AI QUESTION GENERATION (WITH CLEAN RETRY LOGIC)
// ============================================================

async function generateQuestions({ subjects, difficulty, previousQuestions }) {
  const previousText =
    previousQuestions.length === 0
      ? "No previous questions."
      : previousQuestions.map((q, idx) => `${idx + 1}. ${q}`).join("\n");

  const prompt = `
Generate exactly 5 multiple-choice interview preparation questions.

Subjects:
${subjects.join(", ")}

Difficulty:
${difficulty}

Requirements:
1. Questions must be technically correct.
2. Questions must be appropriate for the requested difficulty.
3. Mix the selected subjects.
4. Every question must have exactly 4 options.
5. Only ONE option may be correct.
6. correctAnswer must be an integer from 0 to 3.
7. Give a useful explanation of the answer.
8. Do NOT repeat or closely paraphrase any previous question.
9. Do not use trick questions where multiple answers could reasonably be considered correct.
10. For C++, use modern C++ concepts where appropriate.
11. For DSA, cover concepts such as arrays, strings, linked lists, stacks, queues, trees, graphs, heaps, recursion, greedy, dynamic programming, hashing, or algorithms.
12. For DBMS, cover SQL, normalization, transactions, indexing, keys, joins, concurrency, ACID, query optimization, etc.
13. Do not require internet access to answer the question.
14. Do not mention that the question was generated by AI.

Previous questions for this user:
${previousText}
`;

  // Define structured JSON output schema for Gemini
  const responseSchema = {
    type: Type.OBJECT,
    properties: {
      questions: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            subject: { type: Type.STRING },
            question: { type: Type.STRING },
            options: {
              type: Type.ARRAY,
              items: { type: Type.STRING }
            },
            correctAnswer: { type: Type.INTEGER },
            explanation: { type: Type.STRING }
          },
          required: ["subject", "question", "options", "correctAnswer", "explanation"]
        }
      }
    },
    required: ["questions"]
  };

  const maxRetries = 3;
  let lastError;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are an expert technical interviewer and educator.",
          responseMimeType: "application/json",
          responseSchema: responseSchema,
        }
      });

      if (!response.text) {
        throw new Error("AI returned an empty response.");
      }

      const parsed = JSON.parse(response.text);
      return parsed.questions;
    } catch (error) {
      lastError = error;
      console.warn(`Gemini API attempt ${attempt} failed: ${error.message}`);

      // If server is overloaded (503/429), pause before retrying
      if (attempt < maxRetries) {
        await new Promise((resolve) => setTimeout(resolve, 2000));
      }
    }
  }

  throw lastError;
}


// ============================================================
// SAVE QUESTIONS
// ============================================================

function saveQuestions({ userId, questions, difficulty }) {
  const insert = db.prepare(`
    INSERT INTO questions (
      user_id,
      question_hash,
      subject,
      difficulty,
      question,
      options,
      correct_answer,
      explanation,
      created_at
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  const transaction = db.transaction((items) => {
    for (const question of items) {
      const hash = hashQuestion(question.question);

      if (questionAlreadyExists(userId, hash)) {
        continue;
      }

      insert.run(
        userId,
        hash,
        question.subject,
        difficulty,
        question.question,
        JSON.stringify(question.options),
        question.correctAnswer,
        question.explanation,
        new Date().toISOString()
      );
    }
  });

  transaction(questions);
}


// ============================================================
// GENERATE QUIZ ENDPOINT
// ============================================================

app.post("/api/generate-quiz", async (req, res) => {
  try {
    const { userId, subjects, difficulty } = req.body;

    // Validation
    if (typeof userId !== "string" || userId.length < 3 || userId.length > 100) {
      return res.status(400).json({ error: "Invalid userId." });
    }

    if (!Array.isArray(subjects) || subjects.length === 0) {
      return res.status(400).json({ error: "At least one subject is required." });
    }

    const allowedSubjects = ["DSA", "DBMS", "C++"];
    const cleanSubjects = subjects.filter((s) => allowedSubjects.includes(s));

    if (cleanSubjects.length === 0) {
      return res.status(400).json({ error: "Invalid subjects." });
    }

    const allowedDifficulties = ["easy", "medium", "hard"];
    if (!allowedDifficulties.includes(difficulty)) {
      return res.status(400).json({ error: "Invalid difficulty." });
    }

    ensureUser(userId);
    const previousQuestions = getPreviousQuestions(userId);

    let questions = [];
    let attempts = 0;

    while (questions.length < 5 && attempts < 3) {
      attempts++;

      const generated = await generateQuestions({
        subjects: cleanSubjects,
        difficulty,
        previousQuestions: [
          ...previousQuestions,
          ...questions.map((q) => q.question)
        ],
      });

      for (const question of generated) {
        const hash = hashQuestion(question.question);
        const duplicateInDatabase = questionAlreadyExists(userId, hash);
        const duplicateInCurrentQuiz = questions.some(
          (q) => hashQuestion(q.question) === hash
        );

        if (!duplicateInDatabase && !duplicateInCurrentQuiz) {
          questions.push(question);
        }

        if (questions.length === 5) break;
      }
    }

    if (questions.length < 5) {
      return res.status(500).json({
        error: "Could not generate 5 unique questions. Please try again.",
      });
    }

    saveQuestions({ userId, questions, difficulty });

    const responseQuestions = questions.map((question, index) => ({
      id: Date.now() + index,
      subject: question.subject,
      question: question.question,
      options: question.options,
      correctAnswer: question.correctAnswer,
      explanation: question.explanation,
    }));

    res.json({ questions: responseQuestions });
  } catch (error) {
    console.error("Generate quiz error:", error);
    res.status(500).json({
      error: "Something went wrong while generating the quiz.",
    });
  }
});


// ============================================================
// HISTORY ENDPOINT
// ============================================================

app.get("/api/history/:userId", (req, res) => {
  try {
    const userId = req.params.userId;

    const rows = db
      .prepare(`
        SELECT
          id,
          subject,
          difficulty,
          question,
          options,
          correct_answer,
          explanation,
          created_at
        FROM questions
        WHERE user_id = ?
        ORDER BY created_at DESC
        LIMIT 200
      `)
      .all(userId);

    const questions = rows.map((row) => ({
      id: row.id,
      subject: row.subject,
      difficulty: row.difficulty,
      question: row.question,
      options: JSON.parse(row.options),
      correctAnswer: row.correct_answer,
      explanation: row.explanation,
      createdAt: row.created_at,
    }));

    res.json({ questions });
  } catch (error) {
    console.error("History error:", error);
    res.status(500).json({ error: "Could not load history." });
  }
});


// ============================================================
// HEALTH CHECK
// ============================================================

app.get("/", (req, res) => {
  res.json({
    status: "ok",
    message: "AI Quiz Backend is running.",
  });
});


// ============================================================
// START SERVER
// ============================================================

app.listen(PORT, "0.0.0.0", () => {
  console.log(AI Quiz backend running on port ${PORT});
});